# Generated by Django 2.2.10 on 2020-06-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default='Politica', max_length=200),
        ),
    ]
